version: "3.1"

services:
  db:
    image: postgres:latest
    ports:
      - 5423:5432
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ""
  db_api:
    build:
      context: backend/middleware
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:80
    links:
      - db
