server:
  ENV: 'development'
  HOSTNAME: 'http://localhost:5000'
  DEBUG: True
  TESTING: True
  PORT: 5000
  NAME: 'middleware'
  SQLALCHEMY_DATABASE_URI: 'postgres://user:password@localhost:5432/test'
  SQLALCHEMY_TRACK_MODIFICATIONS: False
  SQLALCHEMY_ECHO: False
